services:
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "${PORT}:80"
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ./html:/var/www/html
