services:
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "${PORT}:80"
    volumes:
      - ./html:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ./html:/var/www/html
